export const FLAG_MAP: Record<string, string> = {
  'Belgium': 'be',
  'France': 'fr',
  'Croatia': 'hr',
  'Brazil': 'br',
  'Uruguay': 'uy',
  'Spain': 'es',
  'England': 'gb-eng',
  'Japan': 'jp',
  'Senegal': 'sn',
  'Serbia': 'rs',
  'Switzerland': 'ch',
  'Mexico': 'mx',
  'South Korea': 'kr',
  'Australia': 'au',
  'Denmark': 'dk',
  'Iran': 'ir',
  'Saudi Arabia': 'sa',
  'Poland': 'pl',
  'Germany': 'de',
  'Argentina': 'ar',
  'Portugal': 'pt',
  'Tunisia': 'tn',
  'Costa Rica': 'cr',
  'Morocco': 'ma',
  'Wales': 'gb-wls',
  'Netherlands': 'nl',
  'Ghana': 'gh',
  'Cameroon': 'cm',
  'Qatar': 'qa',
  'Ecuador': 'ec',
  'USA': 'us',
  'Canada': 'ca'
};
